[env]
platform = platformio/espressif32@6.11.0
framework = arduino
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson@^6.21.6
	jgromes/RadioLib@^7.6.0
	knolleary/PubSubClient@^2.8.0
    https://github.com/bertrik/minishell
    alanswx/ESPAsyncWiFiManager@^0.31.0
    ESP32Async/ESPAsyncWebServer@^3.10.3

[platformio]
default_envs = seeed_xiao_esp32s3
src_dir = .

[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3

